// eslint-disable-next-line camelcase
import { Bebas_Neue, Outfit, Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation";

// eslint-disable-next-line new-cap
const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas",
});

// eslint-disable-next-line new-cap
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
});

// eslint-disable-next-line new-cap
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bebas.variable} ${outfit.variable} ${montserrat.variable} flex justify-center items-center flex-col bg-parts-gray-100`}
      >
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
